### PR TITLE
* STS-939. Added JSON content-type request wrapper for request bodies that are JSON for parameter binding.

### PR DESCRIPTION
**Pull request by rgrashel**
…

### CODE REVIEW

**Comment by iluvtr** [comment]
Hi Rick. I think that the way you solved the parsing of JSON bodies with
the interface ContentTypeWrapper is really smart. But you're thightly
forcing that every JSON body will be processed by the
JsonContentTypeWrapper wich uses Jackson library. What if I want to use
Gson or another library? With this way I just can't.
In addition not every request body will be JSON. What about XML bodies?

I propose a way to solve this issues: Create a factory class called
ContentTypeRequestWrapperFactory which will instantate the classed based in
a configuration parameter like this
content_type=qualified_class_name,content_type=qualified_class_name,..
Example: application/json=pe.hernandez.GsonJsonContentTypeWrapper,
application/xml=pe.hernandez.MyXmlContentTypeWrapper

**Comment by rgrashel** [comment]
Again, great comments.

I was already going to solve for this using a pluggable JsonContentTypeWrapper declared in the web.xml file.  But that was going to be limited to JSON.  Although I was going to add one for XML (since Jackson supports that, also).  

However, I like your approach better.  Your approach allows for the adding of new wrappers for other content-type without changing the code.  I like that a lot.  So if a developer wants to pass YAML, they can do that by easily adding a YAML content type wrapper and declaring it in their web.xml.

I will need to refactor the existing MultipartWrapper to get this to work, but that shouldn't be a problem.  In all honesty, the MultipartWrapperFactory implementation is far too complicated.  I think it can easily be reduced to a simple instantiation of ContenTypeWrappers based on the content-type passed in.  No need for a complex factory to do all of this.

Again, thanks for your great comments and feedback.  This kind of feedback is helping to make Stripes even better than it already is.

**Comment by vankeisb** [comment]
Hi folks,

Does it have to use web.xml ?

Can't this be auto-discovered by default, like other Stripes components ?
Maybe a new annot :

@Wrapper(contentType="text/xml")
class MyXmlWrapper ... {
}

?

Cheers

Rémi

2015-08-09 0:48 GMT+02:00 Rick Grashel <notifications@github.com>:

**Comment by vankeisb** [comment]
otoh, you won't change this very often, so it could be a web.xml cont-fig
actually. It's not something that app devs will use, it's more of a
"franework" thing from what I understand...

Cheers

Rémi

2015-08-09 12:03 GMT+02:00 VANKEISBELCK Remi <remi@rvkb.com>:

**Comment by iluvtr** [comment]
Sounds better. It could work like  Interceptors.

**Comment by iluvtr** [comment]
We could have an annotation @Produces(mediaType), autodiscover by the
Extensions.Package parametro and,  register classes by a parameter too

**Comment by rgrashel** [comment]
I think we've started talking about two different things that are honestly different than this pull request.  This feature is simply to extend the ability for Stripes to parse parameters for different request-body content types like MultipartWrapper does.  

This has nothing to do with is @Accepts or @Produces (in JAX-RS parlance)  which would be declared at an event handler level.  By doing this, you then could expose (through an OPTIONS verb call against the handler) what content-type an event handler can accept and produce... and actually throw an exception back to the caller if they try to violate that contact.  That is potentially a good enhancement, but I'm not sure not having this behavior this should gate a v1.7 release.  Maybe a v1.7.1 could include this capability.  

For this pull request, Stripes will come out of the box with a JsonContentTypeHandler that can extract request body parameters from JSON (just like MultipartRequests).  I will be making this pluggable so that other content-type handlers can easily added through web.xml.  Although once we have an XML handler, I expect this to be fairly static and nobody will change them.

**Comment by vankeisb** [comment]
Yeah exactly : ain't something you will change often, so it probably
doesn't need auto-discovery.

Cheers

Rémi

2015-08-09 16:05 GMT+02:00 Rick Grashel <notifications@github.com>:

**Pull request merged**
